blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogApp.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.homePage, name='home'),
    path('create/', views.addBlog, name="create"),
    path('register/', views.signUp, name="signUp"),
    path('login/', views.userLogin, name="login"),
    path('logout/', views.userLogout, name="logout"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('updateBlog/<slug>', views.updateBlog, name='updateBlog'),
    path('deleteBlog/<slug>', views.deleteBlog, name="deleteBlog"),
    path('blogs/<slug:slug>/', views.blogs, name="blogs"),
    path('search/', views.search, name="search"),
    path('delete-account/', views.deleteAccount, name='deleteAccount'),
    path('editProfile/<str:username>/', views.editProfile, name='editProfile'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changeProfilePicture/<str:username>/',
         views.changeProfilePicture, name='changeProfilePicture'),
]

blogApp/models.py
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Profile(AbstractUser):
    email = models.EmailField(unique=True, null=True)
    profilePicture = models.ImageField(null=True, default="saltbae.png")
    occupation = models.CharField(max_length=255, null=True)


class Blog(models.Model):
    title = models.CharField(max_length=150)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.TextField()
    datePublished = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, null=True, blank=True)

    class Meta:
        ordering = ['-datePublished']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

blogApp/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django import forms


class ChangePasswordForm(PasswordChangeForm):
    pass


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'author', 'article']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'article': forms.Textarea(attrs={'class': 'form-control textArea'})
        }


class UserRegister(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'username',
            'occupation',
            'email',
            'password1',
            'password2'
        ]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'occupation': forms.TextInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(UserRegister, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})

    def save(self, commit=True):
        user = super(UserRegister, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']
        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'username', 'email', 'occupation']

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'occupation': forms.TextInput(attrs={'class': 'form-control'})

        }

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})


class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profilePicture']


class DeleteAccountForm(forms.Form):
    confirmation = forms.BooleanField(label='Confirm Account Deletion')

    def clean_confirmation(self):
        confirmation = self.cleaned_data.get('confirmation')
        if not confirmation:
            raise forms.ValidationError(
                'You must confirm the account deletion.')
        return confirmation


class Search(forms.Form):
    query = forms.CharField(label='Search', max_length=100)

blogApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import *
from .models import *
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.urls import reverse


def homePage(request):
    blogs = Blog.objects.all()
    return render(request, 'home.html', {'blogs': blogs})


def userLogout(request):
    logout(request)
    return redirect('login')


def userLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            errorMessage = 'Wrong Username or Password'
            return render(request, 'logIn.html', {'errorMessage': errorMessage})
    return render(request, 'logIn.html')


def signUp(request):
    form = UserRegister()
    if request.method == 'POST':
        # Create a form instance using the submitted data
        form = UserRegister(request.POST)
        # Validate the form
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    return render(request, 'Register.html', {'form': form})


@login_required
def addBlog(request):
    form = BlogForm()
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user  # Assign the logged-in user as the author
            blog.save()
            return redirect('home')
    return render(request, 'CreateBlog.html', {'form': form})


def profile(request, username):
    user = get_object_or_404(Profile, username=username)
    if request.method == 'POST':
        form = ProfilePictureForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('profile', username=username)
    else:
        form = ProfilePictureForm(instance=user)

    context = {
        'user': user,
        'form': form
    }

    return render(request, 'profile.html', context)


@login_required
def changePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Relogin with your new password')
            return redirect('login')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'changePassword.html', {'form': form})


@login_required
def changeProfilePicture(request, username):
    if request.method == 'POST':
        form = ProfilePictureForm(
            request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile', username=username)
    else:
        form = ProfilePictureForm()

    return render(request, 'changeProfilePicture.html', {'form': form})


def editProfile(request, username):
    form = EditProfileForm(instance=request.user)

    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile', username=username)

    return render(request, 'editProfile.html', {'form': form})


def deleteAccount(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        logout(request)
        return redirect('home')
    return render(request, 'deleteAccount.html')


def blogs(request, slug):
    # read/retrieve blogs from db
    context = Blog.objects.get(slug=slug)
    return render(request, 'blog.html', {'context': context})


def updateBlog(request, slug):
    post = Blog.objects.get(slug=slug)  # get the post from db using it's slug
    form = BlogForm(instance=post)
    # form validation
    if request.method == 'POST':
        # pick the blog that is slected to be updated
        form = BlogForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blogs', slug)  # go back to read blog
    return render(request, 'updateBlog.html', {'form': form})


def deleteBlog(request, slug):
    post = Blog.objects.get(slug=slug)
    post.delete()
    return redirect('home')


def search(request):
    query = request.GET.get('query')
    blogs = Blog.objects.filter(Q(title__icontains=query) | Q(
        author__username__icontains=query))
    context = {'blogs': blogs, 'query': query}
    return render(request, 'search.html', context)

blogApp/templates/CreateBlog.html
{% extends 'main.html' %} {% block content %}
<div class="container p-5">
  <div>
    <h3>Add Blog</h3>
  </div>

  <form method="POST">
    {% csrf_token %} {{ form.title.label }} {{ form.title }}
    {{form.article.label }} {{ form.article }} <br />
    <!-- Autofill author field with logged-in user -->
    <input type="hidden" name="author" value="{{ request.user.id }}" />
    <button class="btn btn-primary" type="submit" name="submit">Submit</button>
  </form>
</div>

{% endblock %}

blogApp/templates/blog.html
{% extends 'main.html' %} {% block content %}
<div class="container vw-80">
  <div class="postHead">
    <br />
    <h2>{{ context.title|title }}</h2>
    <h5>{{ context.author }}</h5>
    <small>{{ context.datePublished }}</small>
  </div>
  <div class="texts w-80">
    <p>{{ context.article|linebreaks|urlize }}</p>
  </div>

  <div class="row buttons gap-2">
    {% if context.author == request.user %}
    <button class="btn bg-primary action-btn">
      <a href="{% url 'updateBlog' context.slug %}">Edit</a>
    </button>
    <br />
    <button
      class="btn bg-danger action-btn"
      onclick="alert('Are you sure you want to delete this Blog')"
    >
      <a href="{% url 'deleteBlog' context.slug %}">Delete Blog</a>
    </button>
    {% endif %}
  </div>
</div>
{% endblock %}

blogApp/templates/changePassword.html
{% extends 'main.html' %}
{% block content %}
    <form method="POST" class="form h-50 changePassword mx-auto my-auto" style="min-width: 200px;">
      <h1 class="text-center">Change Password</h1>
      {% csrf_token %}
      <div class="form-group">
        {{ form.old_password.label_tag }} <br>
        {{ form.old_password }}
      </div>
      
      <div class="form-group">
        {{ form.new_password1.label_tag }}<br>
        {{ form.new_password1 }}
      </div>
      
      <div class="form-group">
        {{ form.new_password2.label_tag }}<br>
        {{ form.new_password2 }}
      </div>
      {% if form.errors %}
    <div class="alert alert-danger my-3">
      <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
        {% endfor %}
      </ul>
    </div>
{% endif %}
      <button type="submit" class="btn btn-primary">Change Password</button>
    </form>
 

{% endblock %}

blogApp/templates/changeProfilePicture.html
<!-- edit_profile.html -->
{% extends 'main.html' %}
{% block content %}

    
  <form method="POST" enctype="multipart/form-data" class="form h-auto my-auto mx-auto">
        {% csrf_token %}
        <h4>Change Profile Picture</h4>
        <hr>
        <input type="file" name="profilePicture">
        <button type="submit" class="btn btn-primary">Change Profile Picture</button>
        <hr>
        
     {% if form.errors %}
    <div class="alert alert-danger  mt-2">
      <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
        {% endfor %}
      </ul>
    </div>
{% endif %}
      </form>
        
    
{% endblock %}

blogApp/templates/deleteAccount.html
{% extends 'main.html' %}

{% block content %}


  <form method="POST" action="{% url 'deleteAccount' %}" class="form mx-auto h-50 mt-2">
    <h2>Delete Account</h2>
  <p>Are you sure you want to delete your account? This action cannot be undone.</p>
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete Account</button>
  </form>
  
{% endblock %}

blogApp/templates/editProfile.html
<!-- edit_profile.html -->
{% extends 'main.html' %}
{% block content %}
<div class="edit-p">
  <form method="POST" class="form row">
    <h1>Edit Profile</h1>
    {% csrf_token %}
    <div class="row">
        {{ form.first_name.label }} 
        {{ form.first_name }} 
        {% for error in form.first_name.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
        
        {{ form.last_name.label }} 
        {{ form.last_name }} 
        {% for error in form.last_name.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
    
        {{ form.username.label }} 
        {{ form.username }} 
        {% for error in form.username.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
    
        {{ form.occupation.label }} 
        {{ form.occupation }}
        {% for error in form.occupation.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}

        {{ form.email.label }} 
        {{ form.email }}
        {% for error in form.email.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %} 
        
        
      </div>
      {% if form.errors %}
    <div class="alert alert-danger">
      <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
        {% endfor %}
      </ul>
    </div>
{% endif %}
    <button type="submit" class="btn btn-primary w-100 mx-auto">Save Changes</button>
  </form>
  
  <div class="form my-3 h-75 ">
    <h1>account settings</h1>
    <hr>
        <h4>Change Profile Picture</h4>
        <button class="btn bg-danger my-2 w-100">
        <a href="{% url 'changeProfilePicture' user.username %}">Change Profile Picture</a>
        </button>
        <h4>Delete Account</h4>
        <button class="btn bg-danger my-2 w-100">
        <a href="{% url 'deleteAccount' %}">Delete Account</a>
        </button>
       <h4>Change Password</h4>
        <button class="btn bg-danger w-100">
        <a href="{% url 'changePassword'  %}">Go to Change password</a>
        </button>
      </div>
        
    </div>
{% endblock %}

blogApp/templates/home.html
{% extends 'main.html' %}
{% block content %}
<div class="home-container my-4">
  <h1 class="text-center">Browse Blogs</h1>
  <hr>
  {% for blog in blogs %}
  <div class="container bg-white  each-blog">
    <a href="{% url 'blogs' blog.slug %}"><h4>{{ blog.title|title }}</h4></a>

    <p><a href="{% url 'profile' username=blog.author.username %}">By: {{ blog.author }}</a></p>
      <hr>
    <p>
      {% with truncated_article=blog.article|truncatewords_html:30 %}
        {{ truncated_article }}
        {% if blog.article != truncated_article %}
          <a href="{% url 'blogs' blog.slug %}" class="text-primary" style="text-decoration: underline;">See more</a>
        {% endif %}
      {% endwith %}
    </p>
  </div>
  {% endfor %}
</div>
{% endblock %}

blogApp/templates/logIn.html
{% extends 'main.html' %} {% block content %}
    <form class="form h-50 mx-auto  my-auto shadow-lg" method="POST">
      {% csrf_token %}
       <p class="form-title">Sign in to your account</p>
       <hr>
        <div class="input-container">
          <input type="text" name="username" placeholder="Enter username">
          <span>
          </span>
      </div>
      <div class="input-container">
          <input type="password" name="password" placeholder="Enter password">
        </div>
        {% if errorMessage %}
        <ul class="errorMessage" >
            <li style="color: red; ">{{ errorMessage }}</li>
        </ul>
      {% endif %}
        
         <button type="submit"  name="submit" class="submit">
        Sign in
      </button>

      <p class="signup-link">
        No account?
        <a href="{% url 'signUp' %}">Sign up</a>
      </p>
      
  {% endblock content %}
   </form>   
   
</div>

blogApp/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static '/css/main.css' %}" />
    <script defer src="{% static 'js/bootstrap.js' %}"></script>
    <title>blogApp</title>
  </head>
  <body class="h-100">
    {% include 'nav.html' %}
    <div class="container main-container h-100">
      {% block content %} {% endblock %}
    </div>
    <footer class="footer text-white">
      <p class="text-center">This Project Is made By</p>
      <p class="text-center">Asebto, Marilyn. | Bocabo, John Doe V.</p>
      <p class="text-center">From BSIT 3D</p>
    </footer>
  </body>
</html>

blogApp/templates/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg text-white" style="background-color: rgb(16, 16, 125);">
  <div class="container-fluid">
    <div class="col  d-flex ">
    <h1 class="navbar-brand" href="{% url 'home' %}"><h1>blogApp</h1></a>
    
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav my-2 mb-2 mb-lg-0">
        <li class="nav-item ms-3">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
      </ul>
    </div>
    <div class="col">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">  
      
      
      {% if request.user.is_authenticated %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
        <li class="nav-item ms-3">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
        <li class="nav-item ms-3">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'create' %}">Create Blog</a>
        </li>
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
        <li class="nav-item ms-3">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'profile' request.user.username %}">Profile</a>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
        <li class="nav-item ms-3">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'login' %}">Log in</a>
        </li>
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
        <li class="nav-item ms-3">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'signUp' %}">Sign Up</a>
        </li>
      </ul>
      {% endif %}
      <form method="GET" action="{% url 'search' %}" class="searchForm text-white" >
            <div class="search">
  <div class="search-box">  
    <div class="search-field">
      <input placeholder="Search..." class="input" type="text" name="query" required>
      <div class="search-box-icon">
        <button class="btn-icon-content">
          <i class="search-icon">
            <svg xmlns="://www.w3.org/2000/svg" version="1.1" viewBox="0 0 512 512"><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z" fill="#fff"></path></svg>
          </i>
        </button>
      </div>
    </div>
  </div>
</div>
            
        
    </form>
    </div>
    </div>
    
  </div>
  
</nav>

blogApp/templates/profile.html
{% extends 'main.html' %} {% block content %}
<div class="container row w-100">
<div class="col-4 align-items-start bg-white h-auto shadow-lg my-2">
    <div class="row mx-auto h-50 py-2">
        <img src="{{ user.profilePicture.url }}"></img>
    </div>

    <div class="row mx-auto">
       <h2 class="text-center ">{{ user.first_name }} {{ user.last_name }}</h2>
        <p>@{{ user.username }}</p>
        <p>Occupation:{{ user.occupation }}</p>
        <p>Email: {{ user.email }}</p>
    
        {% if user.username == request.user.username %}
        <button class="btn btn-primary"><a href="{% url 'editProfile' username=user.username %}">Edit Profile</a></button>
        
        {% endif %}

    </div>
</div>

<div class="col home-container my-3 ">
        <h1 class="text-center mt-2">{{ user.username }}'s blogs</h1>
        {% for blog in user.blog_set.all %}
            <div class="container bg-white  each-blog row  mx-auto">
                <a href="{% url 'blogs' blog.slug %}"><h4>{{ blog.title|title }}</h4></a>
                <p>By: <a href="{% url 'profile' username=user.username %}">{{ user.username }}</a></p>
                  <hr>
            <p>
            {% with truncated_article=blog.article|truncatewords_html:30 %}
                {{ truncated_article }}
                {% if blog.article != truncated_article %}
                <a href="{% url 'blogs' blog.slug %}" class="text-primary" style="text-decoration: underline;">See more</a>
                {% endif %}
            {% endwith %}
            </p>
            </div>
        {% empty %}
            <p>No blogs available.</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

blogApp/templates/register.html
  {% extends 'main.html' %}
  {% block content %}
    

  <form method="POST" action="" class="form2 mx-auto bg-white h-50 p-4 my-2 rounded shadow-lg signUpForm">
    <h1>Sign Up</h1>
    <hr>
    {% csrf_token %}
    <div class="row ">
      <div class="col">
        {{ form.first_name.label }} 
        {{ form.first_name }} 
        {% for error in form.first_name.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
        
        {{ form.last_name.label }} 
        {{ form.last_name }} 
        {% for error in form.last_name.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
    
        {{ form.username.label }} 
        {{ form.username }} 
        {% for error in form.username.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
    
        {{ form.occupation.label }} 
        {{ form.occupation }}
        {% for error in form.occupation.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
      </div>
    
      <div class="col ">
        {{ form.email.label }} 
        {{ form.email }}
        {% for error in form.email.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %} 
    
        {{ form.password1.label }} 
        {{ form.password1 }} 
        {% for error in form.password1.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
        
        {{ form.password2.label }} 
        {{ form.password2 }} 
        {% for error in form.password2.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
      </div>
    </div>
     {% if form.errors %}
    <div class="alert alert-danger  mt-2">
      <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
        {% endfor %}
      </ul>
    </div>
{% endif %}
    <button type="submit" name="submit" class="btn btn-primary my-3">Register</button>
   
  </form>

  {% endblock %}

blogApp/templates/search.html
{% extends 'main.html' %} 
{% block content %}
<div class="container d-flex flex-column gap-2">
    <h2>Blogs with "{{ query }}"</h2>
    {% for blog in blogs %}
        <div class="container bg-info-subtle each-blog mx-1">
            <a href="{% url 'blogs' blog.slug %}"><h4>{{ blog.title|title }}</h4></a>
            <p><a href="{% url 'profile' username=blog.author.username %}">By: {{ blog.author }}</a></p>
        </div>
    {% empty %} 
        <p>No blogs available.</p>
    {% endfor %}
</div>
{% endblock %}

blogApp/templates/updateBlog.html
{% extends 'main.html' %} {% block content %}

<div class="container p-5">
  <div>
    <h3>Edit Blog</h3>
  </div>

  <form method="POST">
    {% csrf_token %} {{ form.title.label }} {{ form.title }}
    {{form.article.label }} {{ form.article }} <br />
    <!-- Autofill author field with logged-in user -->
    <input type="hidden" name="author" value="{{ request.user.id }}" />
    <button class="btn btn-primary" type="submit" name="submit">Submit</button>
  </form>
</div>

{% endblock %}